# Generated by Django 5.2.3 on 2025-06-20 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume_checker", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="match",
            options={"verbose_name_plural": "Matches"},
        ),
        migrations.AddField(
            model_name="match",
            name="is_invited_for_interview",
            field=models.BooleanField(default=False),
        ),
    ]
